package graph.layout;

public enum LayoutAlgorithms {

	AUTOMATIC, ORTHOGONAL1, CONCENTRIC, CONVEX, TUTTE, KAMADA_KAWAI, FRUCHTERMAN_REINGOLD, SPRING, DAG, CIRCLE, CIRCLE_CENTER, BOX,
	BALLOON, RADIAL_TREE, TREE, COMPACT_TREE, ISOM, FAST_ORGANIC, ORGANIC, HIERARCHICAL, STACK,
	PARTITION, SPTING2, NODE_LINK_TREE, RADIAL_TREE2, SQUIRED_TREEMAP;
	
}
