package graph.layout;

public enum LayoutAlgorithms {

	CONCENTRIC, TUTTE, KAMADA_KAWAI, FRUCHTERMAN_REINGOLD, SPRING, DAG, CIRCLE, BOX, RANDOM,
	BALLOON, RADIAL_TREE, TREE, COMPACT_TREE, ISOM, FAST_ORGANIC, ORGANIC, HIERARCHICAL, STACK,
	PARTITION, SPTING2, BALLON2;
	
}
